// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUP_bMlgPddsiczfswCKWA_zO8cF5We6I',
    appId: '1:11235750532:web:594336cc46865fc6c208d1',
    messagingSenderId: '11235750532',
    projectId: 'azkar-8786',
    authDomain: 'azkar-8786.firebaseapp.com',
    storageBucket: 'azkar-8786.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0oca6OFZFQA0i_6Ldv4VONad3NXPwQ7g',
    appId: '1:11235750532:android:1a19732360beea59c208d1',
    messagingSenderId: '11235750532',
    projectId: 'azkar-8786',
    storageBucket: 'azkar-8786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWK2Z_d8fv_7hbAvnYTyspL6Z7qzHEf0A',
    appId: '1:11235750532:ios:59ba861007b52431c208d1',
    messagingSenderId: '11235750532',
    projectId: 'azkar-8786',
    storageBucket: 'azkar-8786.appspot.com',
    iosBundleId: 'com.example.azkaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWK2Z_d8fv_7hbAvnYTyspL6Z7qzHEf0A',
    appId: '1:11235750532:ios:59ba861007b52431c208d1',
    messagingSenderId: '11235750532',
    projectId: 'azkar-8786',
    storageBucket: 'azkar-8786.appspot.com',
    iosBundleId: 'com.example.azkaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUP_bMlgPddsiczfswCKWA_zO8cF5We6I',
    appId: '1:11235750532:web:f330ec751940f79ac208d1',
    messagingSenderId: '11235750532',
    projectId: 'azkar-8786',
    authDomain: 'azkar-8786.firebaseapp.com',
    storageBucket: 'azkar-8786.appspot.com',
  );
}
