default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
     sh "flutter clean"
     sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
       app: "1:11235750532:android:1a19732360beea59c208d1",
       firebase_cli_token: "1//03JrQzLux1MCQCgYIARAAGAMSNwF-L9IrcLkM-SELGJ2vzCEThOKOJ3Ul35aj7fqkxrqjl4NIDFgViZ_cicTscK0MPK75iX42xQ0",
       android_artifact_type: "APK",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
       testers: "mohammedmego15@gmail.com",
       release_notes: "Fisrt Test Fastlane with Firebase App Distribution"
     )
   end
 end