default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
     sh "flutter clean"
     sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
       app: "1:383408612193:android:da0f9d86c0a8051e4c5b20",
       firebase_cli_token: "1//037QMytKcbrN1CgYIARAAGAMSNwF-L9IrubOhcSDpE35PIn4U6GViq6acDTlrYsinW9ozUlpF-EIL-qeco9yaDNgLx91MAvsc6WY",
       android_artifact_type: "APK",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
       debug: true
       testers: "mohammedmego15@gmail.com",
       release_notes: "Fisrt Test Fastlane with Firebase App Distribution"
     )
   end
 end