name: Android Fastlane with Firebase App Distribution Workflow
 
on:
  push:
    branches:
      - main # The branch that you would like to run the workflow when you push into it.

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "temurin"

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.0"
        bundler-cache: true
        working-directory: android

    - name: Ensure Linux platform is added
      run: bundle lock --add-platform x86_64-linux
      working-directory: android

    - name: Build and Distribute App
      run: |
        bundle exec fastlane android firebase_distribution
      working-directory: android
